version: '3'

services:

  elasticsearch:
    container_name: hans-elasticsearch
    build: Dockerfile-elastic
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
      - TZ=Asia/Jakarta
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data-es:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  data-es:
