version: '3'

services:

  nginx:
    container_name: hans-nginx
    build: Dockerfile-nginx
    environment:
      - TZ=Asia/Jakarta
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf